name: Crawl Selected Heartland Hub Institutions

on: workflow_dispatch

jobs:
  crawl_uiowa:
    env:
      id: uiowa
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8" ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: crawl feed
        working-directory: ./
        run: python main.py -i $id
      - name: Upload crawl data to artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.id }}_data
          path: ${{ env.id }}.json
  
